### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sebthom** [hyperxpro/Brotli4j#1]
I'd like to migrate from the unmaintained project https://github.com/MeteoGroup/jbrotli to your project, however Brotli4j is currently only released under GPL. 

GPL makes it nearly impossible to use Brotli4j in any project in the Java eco system. None of the popular Java frameworks/libraries (Netty, Spring, Quarkus, Dropwizard, Grails, Wicket...) is released under GPL. We are also releasing our open source code under either Apache or Eclipse license.

I am not sure if your license choice is actually legal as you are linking against/using brotli which is released under MIT license.

Please reconsider your license choice and either switch to a permissive license (BSD, MIT, Apache) or dual license the code.

A good overview of OS licenses can be found here https://choosealicense.com/appendix/

Thanks a lot for your good work!

**Comment by hyperxpro** [comment]
I agree with you. GPL ain't right for this project. I'm gonna migrate to Apache License 2.0.

Probably by end of this week, I will add support for macOS binary and release under Apache License 2.0.

**Comment by sebthom** [comment]
Awesome!

**Comment by slandelle** [comment]
A good deal of the code in this repo actually originates from Brotli's official repository, eg https://github.com/google/brotli/blob/master/java/org/brotli/wrapper/dec/DecoderJNI.java vs https://github.com/hyperxpro/Brotli4j/blob/main/brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/DecoderJNI.java.

Why not keep the original MIT license? This would avoid any license conflict and guarantee compatibility with Apache 2 license.

**Comment by sebthom** [comment]
sounds good too.

**Comment by hyperxpro** [comment]
I will keep Brotli's original license (MIT) in Brotli source files. Rest source file will contain Apache License 2.0.
