### ISSUE TITLE
Is the implementation thread safe

### ISSUE THREAD

**Issue by harshal-dupare** [hyperxpro/Brotli4j#108]
In my use-case I need the brotli compressor to be thread safe, just wanted to enquire if it is thread safe or not?

**Comment by hyperxpro** [comment]
No, Encoder and Decoders are not thread safe. Thread safety should be done at your application level. Consider delegation the Encoders and Decoders to make it thread safe.

**Comment by hyperxpro** [comment]
No, Encoder and Decoders are not thread safe. Thread safety should be done at your application level. Consider delegation the Encoders and Decoders to make it thread safe.

**Comment by harshal-dupare** [comment]
Thanks for the quick resolution @hyperxpro !
