### ISSUE TITLE
[FEATURE] Add JDK 17 for s390x

### ISSUE THREAD

**Issue by levivic** [hyperxpro/Brotli4j#116]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Could you add jdk17 support for s390x platform? Is there a blocker preventing this from happening?

**Comment by hyperxpro** [comment]
s390x will work fine on JDK 17 since we compile s390x with JDK 8. However, it's not released as of now but it will be soon by 2nd week of November 2023.

**Comment by levivic** [comment]
Good to know, thanks!

**Comment by hyperxpro** [comment]
Released https://github.com/hyperxpro/Brotli4j/releases/tag/v1.13.0
