### ISSUE TITLE
Unable to compress correctly if input data does not start from 0.

### ISSUE THREAD

**Issue by deshanxiao** [hyperxpro/Brotli4j#126]
**Describe the bug**
Unable to compress correctly if input data does not start from 0.

**To Reproduce**
Call **Encoder.compress(byte[] x, int offset, int length)** will compress all bytes from `x`  (offset > 0)

https://github.com/hyperxpro/Brotli4j/blob/0907a385873def839cb0b88132f62238255bc0d6/brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoder.java#L73

data.length -> length ?

**Expected behavior**
It should only compress the bytes from start to start + len.

**Platform (please complete the following information):**
ubuntu

**Additional context**

**Comment by hyperxpro** [comment]
What it the error? Are you getting corrupted data?

**Comment by hyperxpro** [comment]
Technically, you should compress all data and then finish the encoding with length `0`.

**Comment by deshanxiao** [comment]
I got no error but the output array looks unexpected in length. Here is a very simple example: @hyperxpro 

```
public class Main2 {
    static {
        Brotli4jLoader.ensureAvailability();
    }

    public static void main(String[] args) throws IOException {
        byte[] totalBytes = "abcdefg".getBytes();
        // compress "defg"
        byte[] compressedBytes = Encoder.compress(totalBytes, 3, 4);
        // len(output) == 7 not 4
        byte[] output = Decoder.decompress(compressedBytes, 0, compressedBytes.length);
    }
}
```

**Comment by hyperxpro** [comment]
Okay, looks like a bug.

Would you like to raise a PR at https://github.com/google/brotli?

**Comment by hyperxpro** [comment]
PTAL

https://github.com/google/brotli/pull/1104
