### ISSUE TITLE
Support for Brotli modes

### ISSUE THREAD

**Issue by martin-g** [hyperxpro/Brotli4j#13]
I am migrating https://github.com/rdblue/brotli-codec to Brotli4j and I see that it misses support for Brotli modes:
1) https://github.com/rdblue/brotli-codec/blob/9bbc2bcec1e7307e84552f28e90f20cb3099f189/src/main/java/org/apache/hadoop/io/compress/brotli/BrotliCompressor.java#L44
2) https://www.brotli.org/encode.html#aa6f

Any reason why this is not supported at the moment ? Or it is just something that no one needed so far ?

**Comment by hyperxpro** [comment]
Brotli4j uses Google's Brotli Java code. As of now, Google's Brotli Java code does not have `MODE` support. If you can contribute upstream to Google, I will pull the code and merge it with Brotli4j.

**Comment by hyperxpro** [comment]
Fixed by #15

**Comment by martin-g** [comment]
Thanks for merging, @hyperxpro !
Any plans for 1.3.2

**Comment by hyperxpro** [comment]
1.3.2 will release by end of this week or earlier (can't say exact date).
