### ISSUE TITLE
native-osx-x86_64-1.4.0 is empty (missing native lib)

### ISSUE THREAD

**Issue by slandelle** [hyperxpro/Brotli4j#18]
see https://repo1.maven.org/maven2/com/aayushatharva/brotli4j/native-osx-x86_64/1.3.2/ vs https://repo1.maven.org/maven2/com/aayushatharva/brotli4j/native-osx-x86_64/1.4.0/

**Comment by hyperxpro** [comment]
To be fixed by #20
