### ISSUE TITLE
Multi-Release JAR support for module-info

### ISSUE THREAD

**Issue by kashike** [hyperxpro/Brotli4j#25]
`Multi-Release` JAR support to allow for packaging a `module-info` in the artifacts would be nice to have, and is a step beyond #24 which simply calls for an automatic module.

**Comment by hyperxpro** [comment]
Can you do a PR?

**Comment by kashike** [comment]
I was working on one - #26.

**Comment by rlubke** [comment]
Any idea when these module updates will be incorporated?  I'm trying to modularize a project relying on Netty which relies on this library, but the lack of a module name is causing issues.

**Comment by hyperxpro** [comment]
I don't have expertise on modules. It'll be great if you can provide feedback or bring people who can help.

**Comment by rlubke** [comment]
It looks like a PR was opened to address: https://github.com/hyperxpro/Brotli4j/pull/26/commits
