### ISSUE TITLE
Update local brotli copy from upstream

### ISSUE THREAD

**Issue by slandelle** [hyperxpro/Brotli4j#29]
Hey @hyperxpro !

The latest pull from upstream is from 3 months ago.

Upstream has been recently updated with many improvements, both in the C code and in the JNI/Java code.

In particular, https://github.com/google/brotli/issues/880 is probably very interesting.

Could you please refresh the local copy and cut a new release?

Cheers?

**Comment by hyperxpro** [comment]
Sure, will synchronize with upstream soon. However, I will wait for some time before releasing the new version because 1.5.0 was recently released.

Does this sound good?

**Comment by slandelle** [comment]
Sure

**Comment by slandelle** [comment]
Thanks :)

**Comment by hyperxpro** [comment]
Released 1.6.0
