### ISSUE TITLE
Can't load native library

### ISSUE THREAD

**Issue by SettingDust** [hyperxpro/Brotli4j#30]
It's throws a `NullPointer` at
https://github.com/hyperxpro/Brotli4j/blob/main/brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java#L47.

The `libPath` is `/lib/windows-x86_64/brotli.dll` in debugger

Caused by the `in` is null and the `Files#copy` throw it.
```
    public static long copy(InputStream in, Path target, CopyOption... options)
        throws IOException
    {
        // ensure not null before opening file
        Objects.requireNonNull(in);
```

Tried adding natives as dependency.

I'm using Kotlin 1.5.21. OpenJDK 1.8.0.292-1.b10.
Windows 10 64bit

**Comment by hyperxpro** [comment]
Which OS and Architecture?

**Comment by SettingDust** [comment]
> Which OS and Architecture?

Edited

**Comment by hyperxpro** [comment]
If you're using Gradle then you have to manually add the Windows native module.

**Comment by hyperxpro** [comment]
Also, if possible, please share the code project to reproduce.

**Comment by SettingDust** [comment]
It's ok after add windows native manually. But the decompress status is ERROR. How can I debug?

**Comment by hyperxpro** [comment]
Error status is generated due to invalid compressed data. Can you double check the compressed data?

**Comment by SettingDust** [comment]
> Error status is generated due to invalid compressed data. Can you double check the compressed data?

Gotcha! Thanks!
I think we need a help for gradle in README. I try to write sth below. Haven't tested on other systems.
```
    val brotliVersion = "1.5.0"
    implementation("com.aayushatharva.brotli4j:brotli4j:$brotliVersion")
    val operatingSystem = DefaultNativePlatform.getCurrentOperatingSystem()
    if (operatingSystem.isWindows) {
        implementation("com.aayushatharva.brotli4j:native-windows-x86_64:$brotliVersion")
    } else if (operatingSystem.isMacOsX) {
        implementation("com.aayushatharva.brotli4j:native-osx-x86_64:$brotliVersion")
    } else if (operatingSystem.isLinux) {
        if (DefaultNativePlatform.getCurrentArchitecture().isArm) {
            implementation("com.aayushatharva.brotli4j:native-linux-aarch64:$brotliVersion")
        } else {
            implementation("com.aayushatharva.brotli4j:native-linux-x86_64:$brotliVersion")
        }
    }
```

**Comment by hyperxpro** [comment]
Can you please do a PR for this?

**Comment by SettingDust** [comment]
> Can you please do a PR for this?

Okay :D

**Comment by hyperxpro** [comment]
@SettingDust Ping...

**Comment by SettingDust** [comment]
Pong...
