### ISSUE TITLE
Method to calculate maximum possible compression length is missing

### ISSUE THREAD

**Issue by foosmate** [hyperxpro/Brotli4j#36]
For allocating destination buffers it would be convenient to know the maximum possible compression length. Such a method is missing in the current library.

As workaround we are using this (considering the overhead for 1024 as smallest possible window size) ...

    private static int maxCompressedLength(int length) {
        return length + 2 + (length / 1024 + 1) * 3;
    }

**Comment by hyperxpro** [comment]
> return length + 2 + (length / 1024 + 1) * 3;

How did you come up with this calculation? Any reference?

**Comment by Foosmate** [comment]
No, we simply feed the compressor with 1..n random bytes and checks the protocol spec for different window sizes. This leads to the given formula. I would expect that somebody could tell the real story here, but this one works so far for our test cases.
