### ISSUE TITLE
WIndows Server failed to find library file

### ISSUE THREAD

**Issue by zekronium** [hyperxpro/Brotli4j#37]
On Google Cloud, Windows Server 2019 Desktop Experience, the library fails to load.

It seems that the %temp% directories are somehow virtualized.

Navigating to `Environment Variables`, the temp folder is displayed as expected
```
%USERPROFILE%\AppData\Local\Temp
```
which is set properly to
```
C:\Users\some-user\AppData\Local\Temp
```

Although, when echoing `%temp%` in cmd it gives a different result
```
C:\Users\some-user~1\AppData\Local\Temp\2
```

Navigating to this directory, still opens the normal, expected temp directory

When running the app, the library files are extracted here, as per the `%temp%`
```
C:\Users\some-user~1\AppData\Local\Temp\2\com_aayushatharva_brotli4j_1608434778632300
```
Although the JVM seems to be trying to find the files here:
```
Caused by: java.lang.UnsatisfiedLinkError:
C:\Users\some-user\AppData\Local\Temp2\com_aayushatharva_brotli4j_1608434778632300\brotli.dll: Can't find dependent libraries
```

These are effectively the same directories (if you navigate to them)

I am not sure if this can be fixed on your end, or is this a JVM bug (its tested on the latest AdoptOpenJDK)

**Comment by hyperxpro** [comment]
Did you try installing Visual C++ Redistributable?

https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by zekronium** [comment]
Oh 🤦🏼‍♂️ 

Worked
