### ISSUE TITLE
Missing tags for 1.7.0 and 1.7.1

### ISSUE THREAD

**Issue by wltjr** [hyperxpro/Brotli4j#47]
TSIA, it would be nice to have tags for 1.7.0 and 1.7.1 here, at least the latest 1.7.1, thank you!

**Comment by hyperxpro** [comment]
Oops, looks like I forgot to release `drafted` tags and release. Sorry about that. Will fix this ASAP.

**Comment by wltjr** [comment]
No worries, and thanks!
