### ISSUE TITLE
BrotliInputStream IOException: unexpected end of input

### ISSUE THREAD

**Issue by sullis** [hyperxpro/Brotli4j#80]
I have a Java unit test that uses the brotli4j BrotliInputStream to decompress an HTTP response.

The http response is coming from a Netty 4.1.x http server.

The code is available here:
https://github.com/sullis/netty-playground/blob/911a4fe857349dd0230d809725c4cda7b165d6c0/src/test/java/io/github/sullis/netty/playground/HttpServerTest.java

When I run the unit test (brotliWithApacheHttpClient) I see an exception:

```
java.io.IOException: unexpected end of input

	at com.aayushatharva.brotli4j.decoder.Decoder.fail(Decoder.java:113)
	at com.aayushatharva.brotli4j.decoder.Decoder.decode(Decoder.java:159)
	at com.aayushatharva.brotli4j.decoder.BrotliInputStream.read(BrotliInputStream.java:103)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
	at io.github.sullis.netty.playground.HttpServerTest.brotliWithApacheHttpClient(HttpServerTest.java:60)
```

Am I using BrotliInputStream incorrectly?  Or is there a problem with the HTTP response body?

**Comment by sullis** [comment]
I reviewed the implementation of Netty's BrotliEncoder class. 

BrotliEncoder's **finish** method contains this line:

```
ctx.writeAndFlush(writableBuffer, promise);
```

writeAndFlush returns a ChannelFuture.  

The ChannelFuture contains a "cause()" method.  This cause() method is returning an exception.

```
io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```

This commit shows how I got the stack trace:
https://github.com/sullis/netty/commit/63bf966b2fd0ecf028db8d464a96be898e0446e9

**Comment by sullis** [comment]
Draft PR:  https://github.com/netty/netty/pull/13148

**Comment by hyperxpro** [comment]
The problem is with the response body. Try using the `Decompress` class instead of InputStream implementations.

Also, the Netty exception means that the channel was closed before `BrotliEncoder` could finish encoding.

**Comment by sullis** [comment]
> The problem is with the response body. Try using the `Decompress` class instead of InputStream implementations.

This PR uses DirectDecompress to decompress the response body:

https://github.com/sullis/netty-playground/pull/9

```
        DirectDecompress directDecompress = DirectDecompress.decompress(compressedData);
        System.out.println("DirectDecompress result status: " + directDecompress.getResultStatus());
        byte[] decompressedData = directDecompress.getDecompressedData();
        assertNotNull(decompressedData, "decompressedData");
```


When I run the unit test, I see this output:

```
DirectDecompress result status: NEEDS_MORE_INPUT

org.opentest4j.AssertionFailedError: decompressedData ==> expected: not <null>

	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:309)
	at io.github.sullis.netty.playground.HttpServerTest.brotliWithApacheHttpClient(HttpServerTest.java:55)
```

**Comment by hyperxpro** [comment]
This means Netty is not calling close or flush.

**Comment by sullis** [comment]
I set a breakpoint in the Netty server and this is what I observed:

```
BrotliEncoder handlerRemoved is invoked

handlerRemoved invokes finish(ChannelHandlerContext)

finish(ChannelHandlerContext) method invokes writer.close() on the BrotliEncoder.Writer object

BrotliEncoder.Writer.close() creates a Runnable.  The Runnable invokes BrotliEncoder.Writer.finish(ChannelPromise)

finish(ChannelPromise) invokes allocate(true)

finish(ChannelPromise) invokes brotliEncoderChannel.close()

BrotliEncoder.Writer writableBuffer.readableBytes is equal to 1

finish(ChannelPromise) invokes ctx.writeAndFlush(writableBuffer, promise)

```

After writeAndFlush returns, the promise is populated with an exception:  io.netty.channel.StacklessClosedChannelException

**Comment by hyperxpro** [comment]
Who closes the connection first, Netty or your app?

**Comment by sullis** [comment]
> Who closes the connection first, Netty or your app?

The http client is not closing the connection.  The client request includes the keep-alive header

```
Connection: keep-alive
```

The Apache HttpClient logs this debug info:
```
connection http-outgoing-0 can be kept alive for 3 MINUTES
```

On the server-side, I am seeing this:

```
HttpContentEncoder: encode() calls encodeFullResponse()

encodeFullResponse calls encodeContent

encodeContent calls finishEncode

finishEncode calls encoder.finish()

EmbeddedChannel finish(boolean) calls close()

```

I enabled debug log messages for the Apache HttpClient.  The http response contains a content-length header.  The content-length has the expected value. It matches what I see on the server-side for the compressed content.

https://github.com/sullis/netty-playground/pull/9

**Comment by sullis** [comment]
Additional observations:

The string that I am compressing is:
```
"Hello Hello Hello Hello Hello"
```

When I run this code:
```
        byte[] compressed = Encoder.compress(inputText.getBytes(), StandardCompressionOptions.brotli().parameters());
        System.out.println("inputText: " + inputText);
        System.out.println("compressed length: " + compressed.length);
        System.out.println("compressed: " + Arrays.toString(compressed));
```

I observe this output:
```
inputText: Hello Hello Hello Hello Hello
compressed length: 18
compressed: [27, 28, 0, 0, 4, 38, 114, -92, 25, 70, 114, 107, 123, -48, 19, -121, -72, 58]
```

The Netty http response returns a slightly different byte array.

```
HTTP response compressedData length: 18
HTTP response compressedData: [11, 14, 0, 0, 4, 38, 114, -92, 25, 70, 114, 107, 123, -48, 19, -121, -72, 58]
DirectDecompress result status: NEEDS_MORE_INPUT
```

**Comment by sullis** [comment]
I opened a PR in the Netty project: 
https://github.com/netty/netty/pull/13165

**Comment by hyperxpro** [comment]
I will investigate this tomorrow.

**Comment by sullis** [comment]
> ```
> DirectDecompress result status: NEEDS_MORE_INPUT
> 
> org.opentest4j.AssertionFailedError: decompressedData ==> expected: not <null>
> 
> ```

Netty BrotliEncoder fix: https://github.com/netty/netty/pull/13165

**Comment by sullis** [comment]
BrotliEncoder fix was merged this morning:
https://github.com/netty/netty/pull/13165

Netty 4.1.88 SNAPSHOT looks good ✅ 
https://github.com/sullis/netty-playground/pull/13

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/30938/216403125-eb200cb1-2f97-4136-9a09-f374f5af10e1.png">

**Comment by hyperxpro** [comment]
Thanks!
