### ISSUE TITLE
Native libraries libbrotli.dylib are missing in version 1.9.0

### ISSUE THREAD

**Issue by sinedsem** [hyperxpro/Brotli4j#81]
Hi, I found that jars like native-osx-aarch64-1.9.0.jar doesn't have lib folder while native-osx-aarch64-1.8.0.jar have. It makes impossible to use version 1.9.0 at least on my Mac.

**Comment by hyperxpro** [comment]
It's there, I opened up the `native-osx-aarch64-1.9.0.jar` and the native lib is present.

![Screenshot (42)](https://user-images.githubusercontent.com/24762260/217316950-fbb6ebda-518d-4297-9a2a-8c9efe53c8bd.png)

**Comment by sinedsem** [comment]
Hi, it seems like I made wrong investigation of the issue I have, I'll open another issue.
